### ISSUE TITLE
Money balance unchanged after login

### ISSUE THREAD

**Issue by krisdestruction** [ChristopherLMiller/SpoutBonus#1]
My test case is as follows:
1. Have all plugins installed, clear/change the SpoutWallet date if needed
2. Check money through the console or Econ save files
3. Login
4. Check money through the console or Econ save files
5. Money is not added to the BOSEconomy account. On-screen message also says adding 0.0 to account.

Screenshot:
http://terrismc.info/profile/1135620/pics/detail/album_id/119614#pid=631809

Test Server:
test.terrismc.info:25568

**Comment by ChristopherLMiller** [comment]
can you pastebin your config file?  looking over my code it looks correct but i want to verify that the amount is being read from the file correctly.

**Comment by krisdestruction** [comment]
http://pastebin.com/0XdfKn6P

**Comment by ChristopherLMiller** [comment]
yeah i can confirm the issue on my test server as well at this point. gonna look into it and hopefully i can push a new build tonight

**Comment by krisdestruction** [comment]
Ahh maybe you should automate tests :/

**Comment by ChristopherLMiller** [comment]
here is the new version to test while i wait on bukkitdev http://dl.dropbox.com/u/12900238/spoutbonus-1.2.3-SNAPSHOT.jar

**Comment by krisdestruction** [comment]
Work work! Gonna test it

**Comment by krisdestruction** [comment]
It works! Thanks :D
